export const IDX_STOCKS = [
  { s: 'BBCA', n: 'Bank Central Asia' },
  { s: 'BBRI', n: 'Bank Rakyat Indonesia' },
  { s: 'BMRI', n: 'Bank Mandiri' },
  { s: 'TLKM', n: 'Telekomunikasi Indonesia' },
  { s: 'ASII', n: 'Astra International' },
  { s: 'GOTO', n: 'GoTo Gojek Tokopedia' },
  { s: 'UNVR', n: 'Unilever Indonesia' },
  { s: 'ICBP', n: 'Indofood CBP Sukses' },
  { s: 'INDF', n: 'Indofood Sukses Makmur' },
  { s: 'KLBF', n: 'Kalbe Farma' },
  { s: 'ADRO', n: 'Adaro Energy Indonesia' },
  { s: 'PGAS', n: 'Perusahaan Gas Negara' },
  { s: 'SMGR', n: 'Semen Indonesia' },
  { s: 'BYAN', n: 'Bayan Resources' },
  { s: 'ANTM', n: 'Aneka Tambang' },
  { s: 'BBNI', n: 'Bank Negara Indonesia' },
  { s: 'CPIN', n: 'Charoen Pokphand Indonesia' },
  { s: 'GGRM', n: 'Gudang Garam' },
  { s: 'HMSP', n: 'HM Sampoerna' },
  { s: 'ITMG', n: 'Indo Tambangraya Megah' },
];
